CREATE TABLE customers
(
customer_id int PRIMARY KEY,
customer_name VARCHAR(50),
signup_date DATE,
city VARCHAR(50)
);

CREATE TABLE products
(
product_id INT PRIMARY KEY,
product_name VARCHAR(70),
category VARCHAR(50),
price FLOAT
);

CREATE TABLE orders
(
order_id INT PRIMARY KEY,
customer_id INT,
product_id INT,
order_date DATE,
quantity INT
);
)

SELECT * FROM customers;
SELECT * FROM products;
SELECT * FROM orders;

-- List all customers and their total number of orders.

SELECT 
  c.customer_id,
  c.customer_name,
  COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o
  ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name;

-- Find total revenue generated by each customer.

SELECT
  c.customer_id,
  c.customer_name,
  SUM(o.quantity * p.price) AS total_revenue
FROM customers c
JOIN orders o
  ON c.customer_id = o.customer_id
JOIN products p
  ON o.product_id = p.product_id
GROUP BY c.customer_id, c.customer_name;

-- Which product category generates the highest revenue?

SELECT
  p.category,
  SUM(o.quantity * p.price) AS total_revenue
FROM orders o
JOIN products p
  ON o.product_id = p.product_id
GROUP BY p.category
ORDER BY total_revenue DESC
LIMIT 1;


-- Find the top 3 best-selling products by quantity sold.

SELECT
  p.product_name,
  SUM(o.quantity) AS total_quantity_sold
FROM orders o
JOIN products p
  ON o.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_quantity_sold DESC
LIMIT 3;


-- Find customers who placed more than 2 orders in the last 30 days.

SELECT
  customer_id,
  COUNT(*) AS order_count
FROM orders
WHERE order_date >= CURRENT_DATE - INTERVAL '30 days'
GROUP BY customer_id
HAVING COUNT(*) > 2;

-- Calculate monthly revenue trends.

SELECT
  DATE_TRUNC('month', o.order_date) AS month,
  SUM(o.quantity * p.price) AS monthly_revenue
FROM orders o
JOIN products p
  ON o.product_id = p.product_id
GROUP BY month
ORDER BY month;

-- Identify the first and most recent order date for each customer.

SELECT
  customer_id,
  MIN(order_date) AS first_order_date,
  MAX(order_date) AS latest_order_date
FROM orders
GROUP BY customer_id;

-- Identify repeat customers (customers with more than 1 order).

SELECT
  customer_id,
  COUNT(*) AS total_orders
FROM orders
GROUP BY customer_id
HAVING COUNT(*) > 1;

-- Find customers who have never placed an order.

SELECT
  c.customer_id,
  c.customer_name
FROM customers c
LEFT JOIN orders o
  ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;

-- Calculate average order value per customer.

SELECT
  customer_id,
  AVG(order_value) AS avg_order_value
FROM (
  SELECT
    o.order_id,
    o.customer_id,
    SUM(o.quantity * p.price) AS order_value
  FROM orders o
  JOIN products p
    ON o.product_id = p.product_id
  GROUP BY o.order_id, o.customer_id
) sub
GROUP BY customer_id;

-- Rank customers by total revenue

SELECT
  customer_id,
  total_revenue,
  RANK() OVER (ORDER BY total_revenue DESC) AS revenue_rank
FROM (
  SELECT
    o.customer_id,
    SUM(o.quantity * p.price) AS total_revenue
  FROM orders o
  JOIN products p
    ON o.product_id = p.product_id
  GROUP BY o.customer_id
) t;

-- Most purchased product per customer

SELECT
  customer_id,
  product_name,
  total_quantity
FROM (
  SELECT
    o.customer_id,
    p.product_name,
    SUM(o.quantity) AS total_quantity,
    RANK() OVER (
      PARTITION BY o.customer_id
      ORDER BY SUM(o.quantity) DESC
    ) AS rnk
  FROM orders o
  JOIN products p
    ON o.product_id = p.product_id
  GROUP BY o.customer_id, p.product_name
) t
WHERE rnk = 1;


-- Customers whose latest order value > previous order

SELECT DISTINCT customer_id
FROM (
  SELECT
    o.customer_id,
    o.order_date,
    SUM(o.quantity * p.price) AS order_value,
    LAG(SUM(o.quantity * p.price)) OVER (
      PARTITION BY o.customer_id
      ORDER BY o.order_date
    ) AS prev_order_value
  FROM orders o
  JOIN products p
    ON o.product_id = p.product_id
  GROUP BY o.customer_id, o.order_date
) t
WHERE order_value > prev_order_value;

